version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 90:90
    volumes:
      - ./:/usr/share/nginx/html

  app:
    image: image_pengouin
    container_name: app
    restart: always
    depends_on:
      - nginx